resources:
  - name: source
    type: git
    source:
      uri: "https://github.com/sirnuke/reverse-rogue-concept.git"
      username: ((github_username))
      password: ((github_access_token))

jobs:
  - name: gradle
    plan:
      - get: source
        trigger: true
      - task: execute-gradle
        file: source/ci/build.yml
        params:
          BUILD_TYPE: snapshot
        vars:
          nexus_username: ((nexus_username))
          nexus_password: ((nexus_password))
